# Generated by Django 5.2.13 on 2026-04-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('TECH', 'Tech'), ('NON_TECH', 'Non-tech')], default='TECH', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='year',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
