# Generated by Django 5.2.13 on 2026-04-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_category_registration_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('TECH', 'Tech'), ('NON_TECH', 'Non-tech'), ('SPORTS', 'Sports'), ('CULTURAL', 'Cultural'), ('WORKSHOP', 'Workshop')], default='TECH', max_length=20),
        ),
    ]
