# Generated by Django 5.2.13 on 2026-04-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Optional event time limit in minutes.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rules',
            field=models.TextField(blank=True, default=''),
        ),
    ]
