# Generated by Django 5.2.13 on 2026-04-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentotp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentotp',
            name='code',
            field=models.CharField(max_length=8),
        ),
    ]
